### ISSUE TITLE
Fix Certificate PDF and Preview to display certificate.issued_at date instead of ceritificate.created_at date.

### ISSUE THREAD

**Issue by Jtoledo88** [4GeeksAcademy/student-external-profile#1872]
The emission of the certificate for an old student of an old cohort is generated with the current date, and that is wrong because the graduation was a year ago

The emission of the certificate must be attached to the date of the cohort and their graduation. For example: If the student graduated on April 1, 2020, and I generate the certificate today, the date must be April 1, 2020. Or at least that I can change the date.

I attach an example of a student that graduated in the cohort FT-V, more than a year ago and his certificate says he graduated yesterday
[https://certificate.breatheco.de/6e15697ae4224ce1dc83e020037fb7d0e11f0f11]

**Comment by alesanchezr** [comment]
You can do it now, make it work so that if `certificate.issued_at` does not exist, then the `certificate.cohort.ending_at` will be shown.

**Comment by alesanchezr** [comment]
its not certificate.created_at its ceriticate.cohort.ending_at
