### ISSUE TITLE
Quitar BREATHECODE como herramienta de la Primera lesson de prework de FS

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/student-external-profile#2658]
En el PREWORK DE FULL STACK 
Decimos en la última parte de esta lección que BREATHECODE es una herramienta obligatoria a tener en cuenta para el curso. Ya esto no es correcto y se debe cambiar, además la mayoría de los links de las herramientas no funcionan se deben revisar y comprobar que estén correctos.

**Comment by alesanchezr** [comment]
Se cambio en intro-to-4geeks
