### ISSUE TITLE
Faltan clusters en la pagina de 4geeks

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/student-external-profile#4705]
Los clusers que salen en los YML no son los unicos, hay mas, que aunque no tienen YML si deberian salir en la [lista del blog](https://4geeksacademy.com/us/blog). Por ejemplo: `javascript bootcamp`

**Comment by URubino4Geeks** [comment]
Si el cluster no tiene el .yml, no importa, igual se tiene que colocar.
