### ISSUE TITLE
Buscar referencias en proveedores ya conocidos (ingles)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/student-external-profile#4779]
Buscar referencias en proveedores ya conocidos para:

Paginas en ingles:
- 🇺🇸 [Machine Learning Bootcamp](https://4geeksacademy.com/us/coding-bootcamps/machine-learning-engineering).
- 🇺🇸 [Full Stack Developer](https://4geeksacademy.com/us/full-stack-developer/full-stack-developer).
- 🇺🇸 [Full stack developer course](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer)
- 🇺🇸 [Online Coding Bootcamp](https://4geeksacademy.com/us/coding-campus/online-coding-bootcamp)

Todos

- [ ] Redactar los articulos (ya el de machine learning esta pq se usara el de chicago reenfocado)
- [ ] [Subirlos a Motherlink](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5011)
- [ ] Buscar articulos de payperclub.
- [ ] Falta tambien publicar los articulos.

**Comment by Jsolis4geeks** [comment]
No entiendo a que te refieres con esto, debo buscar en MotherLink y PaperClub o como lo estabamos haciendo antes?

**Comment by Jsolis4geeks** [comment]
Con los proveedores ya listados en Notion

**Comment by Jsolis4geeks** [comment]
Hay nuevos proveedores

**Comment by Jsolis4geeks** [comment]
Puedes chequear aqui los nuevos proveedores y asi decidir si ponemos mas enlaces en los que ya tenemos o ponemos en estos nuevos.

https://docs.google.com/spreadsheets/d/1MzdQuREbNdexuq3-H_nJbahzvQIncrzo/edit#gid=763993417

Recomiendo en los nuevos para aumentar el numero de refering Domains

**Comment by Jsolis4geeks** [comment]
Ya estan seleccionados los 6 sitios en este Sheet: https://docs.google.com/spreadsheets/d/1MzdQuREbNdexuq3-H_nJbahzvQIncrzo/edit#gid=2001722159

Total ($): 494

**Comment by Jsolis4geeks** [comment]
Para la keyword online coding bootcamp:

![image](https://user-images.githubusercontent.com/118853358/233415577-85045ae1-7278-4085-a013-a18315fde1a4.png)

**Comment by Jsolis4geeks** [comment]
Mind Stick:
- [ ] Waiting for Payment Information
- [ ] Need to write the article that we are going to send

Ingenium Web:
- [ ] Need to write the article that we are going to send

PageKits:
[ ] Need to write the article that we are going to send (article needs to be 700-1000 words long)

HubFlix
- [ ] Need to write the article that we are going to send

WebCom Designs
- [ ] Need to write the article that we are going to send, here they have the requirements wbcomdesigns.   com/wordpress-guest-blog-post/

CodeCondo
- [ ] Need to write the article that we are going to send

**Comment by URubino4Geeks** [comment]
Hay que decidir quién se encargará de escribir los artículos

**Comment by URubino4Geeks** [comment]
Para este issue, vamos a utilizar las primeras 3 keywords prioritariamente y de segundo la 4ta.

**Comment by alesanchezr** [comment]
falta preparar los de papeclick y terminar de publicar todo.

**Comment by Jsolis4geeks** [comment]
Para este Issue en concreto, el de las referencias conseguidas a traves de Link Hunter, tambien estoy a la espera de que se apruebe el template para pedir el contenido, serían 6 artículos que le pediría a los escritores de Fiverr.

**Comment by URubino4Geeks** [comment]
[Aprobado el template para enviar](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5011#issuecomment-1534974879)

**Comment by Jsolis4geeks** [comment]
Ya se  pidieron los articulos y hay 4 listos para revisar y 6 en proceso

**Comment by Jsolis4geeks** [comment]
Contacté todos los proveedores y estoy esperanod approval para enviar 5 articulos.
Hay un proveedor que me pidio que enviara topics y ellos elegian el topic para a partir de ahi redactar el articulo.

Todos estos articulos permiten solo 1 Link en ellos:

- [ ] https://docs.google.com/document/d/1oWCjzY0RUM94RrjZMnjb18omiTa2xEgcUA5re3ZVyK0/edit#heading=h.z15hi9sz0amf
- [ ] https://docs.google.com/document/d/1UrObKtKImCfVER1ILNY7ymDVxCf5OnZtKR-b6P_-Mt0/edit#heading=h.z8g1vul5x86d
- [ ] https://docs.google.com/document/d/1wiT6XuqGmpUu7x3hp_dKihHuQHynAYTlPgxVLPlRoAM/edit#
- [ ] https://docs.google.com/document/d/1uBOyi-tJNqzmLDHBFXGhRAfTOJWTyLkpHQq8Z_tYyZw/edit#

**Comment by Jsolis4geeks** [comment]
Se enviaron los artículos, esperando respuesta, quedan 2 artículos por redactar; 1 de ellos porque tienen que aprobar el Topic y el otro porque los 4 escritores de Fiverr ya están designados a otras labores (1 para LinkBuilding y 3 para el BLog de Latam)
