### ISSUE TITLE
Landing de full stack developer bootcamp tiene las palabras mal

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/student-external-profile#6998]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42209-a2255af90028932f7aebb79bc04db352) 

 a veces dice full stack coding bootcamp

---
**Source URL**:
[https://website-v2-git-fork-g-code7-master-geeksacademy.vercel.app/us/landing/full-stack-developer-bootcamp](https://website-v2-git-fork-g-code7-master-geeksacademy.vercel.app/us/landing/full-stack-developer-bootcamp)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 121.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x879</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1985
