### ISSUE TITLE
Falta agregar el texto y candado de la izquierda en seccion de powered by stripe

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/student-external-profile#7388]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/e4fd41dd-0e05-4b96-9ef1-7e2310d33ce0)

**Comment by tommygonzaleza** [comment]
<img width="1431" alt="Screenshot 2024-05-21 at 3 43 51 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/f5748ab2-82a7-4d0c-a4b7-9eb8a563e38d">

**Comment by ArielCalisaya** [comment]
listo!
