### ISSUE TITLE
Cambios en la notificacion de projectos mandatorios

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/student-external-profile#7926]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45333-6dfb42f072d14f4efdae22410cabcd5a) 

---
**Source URL**:
[https://4geeks.com/cohort/4geeks-fs-1/full-stack-self-pace/v2](https://4geeks.com/cohort/4geeks-fs-1/full-stack-self-pace/v2)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1866x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1.1</td></tr></table>

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-47912&t=6hgw9BgWw6QOINxU-1

**Comment by tommygonzaleza** [comment]
Will be developed [here](https://github.com/breatheco-de/breatheco-de/issues/7986)
